name: misterfix_provider
description: MisterFix - App do Provedor | Plataforma de Serviços Domésticos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  http: ^1.2.1

  # Estado
  provider: ^6.1.2

  # Armazenamento local
  shared_preferences: ^2.2.3

  # Navegação
  go_router: ^17.3.0

  # Utilitários
  intl: ^0.20.2
  uuid: ^4.4.0

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
